"""add_lesson_type_to_schedule

Revision ID: aaf5ca2b7cf0
Revises: 18bc4814acba
Create Date: 2025-08-27 14:23:23.800035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf5ca2b7cf0'
down_revision = '18bc4814acba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lesson_type', sa.String(length=20), nullable=False, server_default='lecture'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('lesson_type')

    # ### end Alembic commands ###
