"""add_is_favorite_to_course

Revision ID: add_is_favorite_to_course
Revises: 4f134c12710b
Create Date: 2025-08-22 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_favorite_to_course'
down_revision = '4f134c12710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('is_favorite', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course', 'is_favorite')
    # ### end Alembic commands ###

