"""favorites_table

Revision ID: d0746ebf5341
Revises: add_is_favorite_to_course
Create Date: 2025-08-24 17:53:45.254685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0746ebf5341'
down_revision = 'add_is_favorite_to_course'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))

    op.drop_table('user_favorites')
    # ### end Alembic commands ###
